### ISSUE TITLE
submit the actual proper EIP per Boris' request

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ERC-1789#18]

**Comment by bmann** [comment]
Per EIP process and my suggestion ;)

**Comment by lrettig** [comment]
It's here, working on it: https://github.com/lrettig/EIPs/pull/1

**Comment by pet3r-pan** [comment]
> It's here, working on it: [lrettig/EIPs#1](https://github.com/lrettig/EIPs/pull/1)

This was merged. Seems to be fine to close this issue now.

**Comment by lrettig** [comment]
yup thanks
