### ISSUE TITLE
Proposed guiding principles of this initiative

### ISSUE THREAD

**Issue by jpitts** [gitcoinco/ERC-1789#46]
Proposing guiding principles for this effort. These are separate from the principles of funding and governance, which involve the future system. _Principles describe how we do things._

## Guiding Principles of the Block Rewards Funding Initiative

**Responsibility.** - Focus on what you are responsible for. Take bold action, but do so respecting agreements made and understanding consequences.

**Openness.** - All are welcome to participate.

**Transparency.** - All work is performed as transparently as practical.

**Teamwork.** - Work is done in decentralized teams. Participants strive to coordinate action between teams.

**Respectfulness.** - Participants in the initiative respect each other. Participants respect policies and processes adopted by teams.

**Comment by glauseWilde** [comment]
Lets add the telegram community rules as well as suggested here.

https://github.com/ethereum-funding/blockrewardsfunding/issues/37#issuecomment-477934755

**Comment by lrettig** [comment]
Looks like this has been codified, thanks @jpitts! https://github.com/ethereum-funding/docs/blob/master/vision-mission-principles.md
