### ISSUE TITLE
Working Group Calls -- Chatham House Rules vs. Publicly Recorded + Available

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ERC-1789#57]
Hey all,

Here's a topic I want to bring up on our next call.

When we originally scheduled the weekly calls ( https://github.com/ethereum-funding/blockrewardsfunding/issues/40 ) we agreed to record them.  Since we believe in transparency, we felt that it'd be important to have the calls recorded + publicly available.

We also agreed to Chatnam House Rules (which is -- in my understanding -- everyone's free to use the information in the call, but they aren't free to say who said what).

It has been pointed out to me that these two operating norms are mutually exclusive.  We need to choose one or another..

I invite debate about what the standard operating procedur for the weekly calls ( https://github.com/ethereum-funding/blockrewardsfunding/issues/40 ) should be.

**Comment by lrettig** [comment]
We agreed on Chatham House Rule for the call. Closing, @owocki feel free to reopen if you think there's a to do here.

**Comment by lrettig** [comment]
I think I got this wrong - the decision was the opposite, notes recorded & transparent. Sorry about that. But keeping this closed since a decision was made.
